apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: grafana
  namespace: monitoring
spec:
  virtualhost:
    fqdn: grafana-example.projectcontour.io
  routes:
  - conditions:
    - prefix: /
    services:
    - name: grafana
      port: 3000
