# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
# main branch targets
- target-branch: main
  package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  cooldown:
    default-days: 3
    semver-major-days: 15
  labels:
  - area/dependency
  - release-note/none-required
  groups:
    k8s-dependencies:
      patterns:
      - "k8s.io/*"
- target-branch: main
  package-ecosystem: "gomod"
  directory: "/tools"
  schedule:
    interval: "weekly"
    day: "sunday"
  cooldown:
    default-days: 3
    semver-major-days: 15
  labels:
  - area/tooling
  - release-note/none-required
- target-branch: main
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  cooldown:
    default-days: 3
  labels:
  - area/tooling
  - release-note/none-required
  groups:
    artifact-actions:
      patterns:
      - "actions/upload-artifact"
      - "actions/download-artifact"

# release branch targets
- target-branch: release-1.33
  package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  cooldown:
    default-days: 3
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  labels:
  - area/dependency
  - release-note/none-required
  groups:
    k8s-dependencies:
      patterns:
      - "k8s.io/*"
- target-branch: release-1.33
  package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
    day: "sunday"
  cooldown:
    default-days: 3
  ignore:
  - dependency-name: "*"
    update-types:
    - "version-update:semver-major"
    - "version-update:semver-minor"
  labels:
  - area/tooling
  - release-note/none-required
  groups:
    artifact-actions:
      patterns:
      - "actions/upload-artifact"
      - "actions/download-artifact"


