run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - goimports
  - gosec
  - misspell
  - unconvert
  - unparam

# TODO(jpeach): enable these later:
#  - gocyclo
#  - gocognit

linters-settings:
  misspell:
    ignore-words:
    - clas
    - cancelled
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false

issues:
  exclude:
  # TODO(jpeach): exclude unparam warnings about functions that always recieve
  # the same arguments. We should clean those up some time.
  - always receives
  exclude-rules:
  - path: zz_generated
    linters:
    - goimports

