run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - gofmt
  - goimports
  - revive
  - gosec
  - misspell
  - unconvert
  - unparam
  - goheader
  - gocritic
  - forbidigo

linters-settings:
  misspell:
    ignore-words:
    - clas
    - cancelled
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  goheader:
    template-path: ./hack/license-template.txt

  forbidigo:
    forbid:
      - http.DefaultTransport

issues:
  exclude-rules:
  - linters:
    - unparam
    text: "always receives"
  - path: zz_generated
    linters:
    - goimports
  - path: test/e2e
    linters:
      - bodyclose