run:
  timeout: 10m

linters:
  enable:
  - bodyclose
  - gofmt
  - goimports
  - revive
  - gosec
  - misspell
  - unconvert
  - unparam
  - goheader
  - gocritic

# TODO(jpeach): enable these later:
#  - gocyclo
#  - gocognit

linters-settings:
  misspell:
    ignore-words:
    - clas
    - cancelled
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  goheader:
    template-path: ./hack/license-template.txt

issues:
  exclude:
  # TODO(jpeach): exclude unparam warnings about functions that always receive
  # the same arguments. We should clean those up some time.
  - always receives
  exclude-rules:
  - path: zz_generated
    linters:
    - goimports
  - linters:
    - golint
    text: "var `ingress_https` should be `ingressHTTPS`"
  - linters:
    - golint
    text: "var `ingress_http` should be `ingressHTTP`"
  - linters:
    - golint
    text: "returns unexported type"
  - linters:
    - golint
    text: "don't use ALL_CAPS in Go names; use CamelCase"
  - path: test/e2e
    linters:
      - bodyclose