name: contour
repo: getoutreach/contour
pipelineTemplate: custom_segments
deploymentSegments:
  - name: "ops"
    groupType: GROUP
  - name: "white"
    groupType: GROUP
  - name: "shared-service-white"
    groupType: GROUP
  - name: "shared-service-green"
    groupType: GROUP
  - name: "green"
    groupType: GROUP