toc:
  - title: Introduction
    subfolderitems:
      - page: About Contour and Envoy
        url: /about
  - title: Deploying  
    subfolderitems:
      - page: Basic deployment options
        url: /deploy-options
      - page: AWS with NLB
        url: /deploy-aws-nlb
      - page: TLS support
        url: /tls
      - page: EC2 ELB PROXY protocol
        url: /proxy-proto
      - page: Upgrade
        url: /upgrade
  - title: Architecture and design
    subfolderitems:
      - page: Architecture
        url: /architecture
      - page: API design
        url: /api-design
      - page: Roadmap
        url: /roadmap
  - title: More information
    subfolderitems:
      - page: Troubleshooting
        url: /troubleshooting
      - page: Image tagging policy
        url: /tagging
      - page: FAQ
        url: /FAQ