// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	dag "github.com/projectcontour/contour/internal/dag"
	mock "github.com/stretchr/testify/mock"
)

// BuilderType is an autogenerated mock type for the BuilderType type
type BuilderType struct {
	mock.Mock
}

// Build provides a mock function with given fields:
func (_m *BuilderType) Build() *dag.DAG {
	ret := _m.Called()

	var r0 *dag.DAG
	if rf, ok := ret.Get(0).(func() *dag.DAG); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dag.DAG)
		}
	}

	return r0
}
