// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/projectcontour/contour/internal/dag"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDagBuilder creates a new instance of MockDagBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDagBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDagBuilder {
	mock := &MockDagBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDagBuilder is an autogenerated mock type for the DagBuilder type
type MockDagBuilder struct {
	mock.Mock
}

type MockDagBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDagBuilder) EXPECT() *MockDagBuilder_Expecter {
	return &MockDagBuilder_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockDagBuilder
func (_mock *MockDagBuilder) Build() *dag.DAG {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 *dag.DAG
	if returnFunc, ok := ret.Get(0).(func() *dag.DAG); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dag.DAG)
		}
	}
	return r0
}

// MockDagBuilder_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockDagBuilder_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
func (_e *MockDagBuilder_Expecter) Build() *MockDagBuilder_Build_Call {
	return &MockDagBuilder_Build_Call{Call: _e.mock.On("Build")}
}

func (_c *MockDagBuilder_Build_Call) Run(run func()) *MockDagBuilder_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDagBuilder_Build_Call) Return(dAG *dag.DAG) *MockDagBuilder_Build_Call {
	_c.Call.Return(dAG)
	return _c
}

func (_c *MockDagBuilder_Build_Call) RunAndReturn(run func() *dag.DAG) *MockDagBuilder_Build_Call {
	_c.Call.Return(run)
	return _c
}
