source 'https://rubygems.org'

group :jekyll_plugins do
    gem 'jekyll', '~> 4'
    gem 'jekyll-seo-tag', '~> 2.6', '>= 2.6.1' # Automatically create SEO tags
    gem 'jekyll-sitemap', '~> 1.3', '>= 1.3.1' # Create a sitemap using the official Jekyll sitemap gem
    gem 'jekyll-feed', '~> 0.12.1' # Create an Atom feed using the official Jekyll feed gem
    gem 'jekyll-relative-links', '~> 0.6.1' # Used to auto generate md links to html links
    gem 'jekyll-paginate', '~> 1.1' # pagination object for collections (e.g. posts)
    gem 'html-proofer', '~> 3.13' # Link validation
    gem "jekyll-github-metadata", github: "jekyll/github-metadata" # TODO fork repo and update github link reference
    gem 'jekyll-optional-front-matter', '~> 0.3.2' # Parse Markdown files that do not have front-matter callouts
    gem 'jekyll-titles-from-headings', '~> 0.5.3' # pull the page title from the first Markdown heading when none is specified.)
    gem 'jekyll-readme-index', '~> 0.3.0'
end
