---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour-certgen
  namespace: heptio-contour
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: contour
  namespace: heptio-contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contour-certgen
subjects:
- kind: ServiceAccount
  name: contour-certgen
  namespace: heptio-contour
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: contour-certgen
  namespace: heptio-contour
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
  - create
  - get
  - put
  - post
  - patch
---
apiVersion: batch/v1
kind: Job
metadata:
  name: contour-certgen
  namespace: heptio-contour
spec:
  template:
    metadata:
      labels:
        app: "contour-certgen"
    spec:
      containers:
      - name: contour
        image: gcr.io/heptio-images/contour:master
        command:
        - contour
        - certgen
        - --incluster
        - --kube
      restartPolicy: Never
      serviceAccountName: contour-certgen
  parallelism: 1
  completions: 1
  backoffLimit: 1
