# This kustomize file can be used as an example for deploying Contour with custom ClusterRole and Role that could
# change Contour to watch namespaced resources plus cluster-scoped GatewayClass
# It changes the current cluster-wide RBAC rules in the example deployment manifest to namespaced RBAC rules.
# It is meant to be used together with contour serve --watch-namespaces=<ns> option to restrict
# Contour to a certain namespace.
# It also add a ClusterRole and ClusterRoleBinding to Role that only watches GatwayClass
# Run with:
#   kubectl kustomize examples/namespaced-gatewayapi/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../render/
  - gatewayclass-clusterrole.yaml
patches:
  - patch: |-
      - op: replace
        path: /kind
        value: RoleBinding
      - op: replace
        path: /metadata/name
        value: contour-resources
      - op: replace
        path: /roleRef/kind
        value: Role
      - op: replace
        path: /roleRef/name
        value: contour-resources
      - op: add
        path: /metadata/namespace
        value: projectcontour
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: contour
      version: v1
  - patch: |-
      - op: replace
        path: /kind
        value: Role
      - op: replace
        path: /metadata/name
        value: contour-resources
      - op: add
        path: /metadata/namespace
        value: projectcontour
      - op: replace
        path: /rules/1
        value: |-
          - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways
          - grpcroutes
          - httproutes
          - referencegrants
          - tcproutes
          - tlsroutes
          verbs:
          - get
          - list
          - watch
      - op: replace
        path: /rules/2
        value: |-
          - apiGroups:
          - gateway.networking.k8s.io
          resources:
          - gateways/status
          - grpcroutes/status
          - httproutes/status
          - tcproutes/status
          - tlsroutes/status
          verbs:
          - update
    target:
      group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: contour
      version: v1
