// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNeedLeaderElectionNotification creates a new instance of MockNeedLeaderElectionNotification. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNeedLeaderElectionNotification(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNeedLeaderElectionNotification {
	mock := &MockNeedLeaderElectionNotification{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNeedLeaderElectionNotification is an autogenerated mock type for the NeedLeaderElectionNotification type
type MockNeedLeaderElectionNotification struct {
	mock.Mock
}

type MockNeedLeaderElectionNotification_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNeedLeaderElectionNotification) EXPECT() *MockNeedLeaderElectionNotification_Expecter {
	return &MockNeedLeaderElectionNotification_Expecter{mock: &_m.Mock}
}

// OnElectedLeader provides a mock function for the type MockNeedLeaderElectionNotification
func (_mock *MockNeedLeaderElectionNotification) OnElectedLeader() {
	_mock.Called()
	return
}

// MockNeedLeaderElectionNotification_OnElectedLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnElectedLeader'
type MockNeedLeaderElectionNotification_OnElectedLeader_Call struct {
	*mock.Call
}

// OnElectedLeader is a helper method to define mock.On call
func (_e *MockNeedLeaderElectionNotification_Expecter) OnElectedLeader() *MockNeedLeaderElectionNotification_OnElectedLeader_Call {
	return &MockNeedLeaderElectionNotification_OnElectedLeader_Call{Call: _e.mock.On("OnElectedLeader")}
}

func (_c *MockNeedLeaderElectionNotification_OnElectedLeader_Call) Run(run func()) *MockNeedLeaderElectionNotification_OnElectedLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNeedLeaderElectionNotification_OnElectedLeader_Call) Return() *MockNeedLeaderElectionNotification_OnElectedLeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNeedLeaderElectionNotification_OnElectedLeader_Call) RunAndReturn(run func()) *MockNeedLeaderElectionNotification_OnElectedLeader_Call {
	_c.Run(run)
	return _c
}
