// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NeedLeaderElectionNotification is an autogenerated mock type for the NeedLeaderElectionNotification type
type NeedLeaderElectionNotification struct {
	mock.Mock
}

// OnElectedLeader provides a mock function with given fields:
func (_m *NeedLeaderElectionNotification) OnElectedLeader() {
	_m.Called()
}
