// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStatusMetrics creates a new instance of MockStatusMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusMetrics {
	mock := &MockStatusMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusMetrics is an autogenerated mock type for the StatusMetrics type
type MockStatusMetrics struct {
	mock.Mock
}

type MockStatusMetrics_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusMetrics) EXPECT() *MockStatusMetrics_Expecter {
	return &MockStatusMetrics_Expecter{mock: &_m.Mock}
}

// SetStatusUpdateConflict provides a mock function for the type MockStatusMetrics
func (_mock *MockStatusMetrics) SetStatusUpdateConflict(kind string) {
	_mock.Called(kind)
	return
}

// MockStatusMetrics_SetStatusUpdateConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusUpdateConflict'
type MockStatusMetrics_SetStatusUpdateConflict_Call struct {
	*mock.Call
}

// SetStatusUpdateConflict is a helper method to define mock.On call
//   - kind string
func (_e *MockStatusMetrics_Expecter) SetStatusUpdateConflict(kind interface{}) *MockStatusMetrics_SetStatusUpdateConflict_Call {
	return &MockStatusMetrics_SetStatusUpdateConflict_Call{Call: _e.mock.On("SetStatusUpdateConflict", kind)}
}

func (_c *MockStatusMetrics_SetStatusUpdateConflict_Call) Run(run func(kind string)) *MockStatusMetrics_SetStatusUpdateConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateConflict_Call) Return() *MockStatusMetrics_SetStatusUpdateConflict_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateConflict_Call) RunAndReturn(run func(kind string)) *MockStatusMetrics_SetStatusUpdateConflict_Call {
	_c.Run(run)
	return _c
}

// SetStatusUpdateDuration provides a mock function for the type MockStatusMetrics
func (_mock *MockStatusMetrics) SetStatusUpdateDuration(duration time.Duration, kind string, onError bool) {
	_mock.Called(duration, kind, onError)
	return
}

// MockStatusMetrics_SetStatusUpdateDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusUpdateDuration'
type MockStatusMetrics_SetStatusUpdateDuration_Call struct {
	*mock.Call
}

// SetStatusUpdateDuration is a helper method to define mock.On call
//   - duration time.Duration
//   - kind string
//   - onError bool
func (_e *MockStatusMetrics_Expecter) SetStatusUpdateDuration(duration interface{}, kind interface{}, onError interface{}) *MockStatusMetrics_SetStatusUpdateDuration_Call {
	return &MockStatusMetrics_SetStatusUpdateDuration_Call{Call: _e.mock.On("SetStatusUpdateDuration", duration, kind, onError)}
}

func (_c *MockStatusMetrics_SetStatusUpdateDuration_Call) Run(run func(duration time.Duration, kind string, onError bool)) *MockStatusMetrics_SetStatusUpdateDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateDuration_Call) Return() *MockStatusMetrics_SetStatusUpdateDuration_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateDuration_Call) RunAndReturn(run func(duration time.Duration, kind string, onError bool)) *MockStatusMetrics_SetStatusUpdateDuration_Call {
	_c.Run(run)
	return _c
}

// SetStatusUpdateFailed provides a mock function for the type MockStatusMetrics
func (_mock *MockStatusMetrics) SetStatusUpdateFailed(kind string) {
	_mock.Called(kind)
	return
}

// MockStatusMetrics_SetStatusUpdateFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusUpdateFailed'
type MockStatusMetrics_SetStatusUpdateFailed_Call struct {
	*mock.Call
}

// SetStatusUpdateFailed is a helper method to define mock.On call
//   - kind string
func (_e *MockStatusMetrics_Expecter) SetStatusUpdateFailed(kind interface{}) *MockStatusMetrics_SetStatusUpdateFailed_Call {
	return &MockStatusMetrics_SetStatusUpdateFailed_Call{Call: _e.mock.On("SetStatusUpdateFailed", kind)}
}

func (_c *MockStatusMetrics_SetStatusUpdateFailed_Call) Run(run func(kind string)) *MockStatusMetrics_SetStatusUpdateFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateFailed_Call) Return() *MockStatusMetrics_SetStatusUpdateFailed_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateFailed_Call) RunAndReturn(run func(kind string)) *MockStatusMetrics_SetStatusUpdateFailed_Call {
	_c.Run(run)
	return _c
}

// SetStatusUpdateNoop provides a mock function for the type MockStatusMetrics
func (_mock *MockStatusMetrics) SetStatusUpdateNoop(kind string) {
	_mock.Called(kind)
	return
}

// MockStatusMetrics_SetStatusUpdateNoop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusUpdateNoop'
type MockStatusMetrics_SetStatusUpdateNoop_Call struct {
	*mock.Call
}

// SetStatusUpdateNoop is a helper method to define mock.On call
//   - kind string
func (_e *MockStatusMetrics_Expecter) SetStatusUpdateNoop(kind interface{}) *MockStatusMetrics_SetStatusUpdateNoop_Call {
	return &MockStatusMetrics_SetStatusUpdateNoop_Call{Call: _e.mock.On("SetStatusUpdateNoop", kind)}
}

func (_c *MockStatusMetrics_SetStatusUpdateNoop_Call) Run(run func(kind string)) *MockStatusMetrics_SetStatusUpdateNoop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateNoop_Call) Return() *MockStatusMetrics_SetStatusUpdateNoop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateNoop_Call) RunAndReturn(run func(kind string)) *MockStatusMetrics_SetStatusUpdateNoop_Call {
	_c.Run(run)
	return _c
}

// SetStatusUpdateSuccess provides a mock function for the type MockStatusMetrics
func (_mock *MockStatusMetrics) SetStatusUpdateSuccess(kind string) {
	_mock.Called(kind)
	return
}

// MockStatusMetrics_SetStatusUpdateSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusUpdateSuccess'
type MockStatusMetrics_SetStatusUpdateSuccess_Call struct {
	*mock.Call
}

// SetStatusUpdateSuccess is a helper method to define mock.On call
//   - kind string
func (_e *MockStatusMetrics_Expecter) SetStatusUpdateSuccess(kind interface{}) *MockStatusMetrics_SetStatusUpdateSuccess_Call {
	return &MockStatusMetrics_SetStatusUpdateSuccess_Call{Call: _e.mock.On("SetStatusUpdateSuccess", kind)}
}

func (_c *MockStatusMetrics_SetStatusUpdateSuccess_Call) Run(run func(kind string)) *MockStatusMetrics_SetStatusUpdateSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateSuccess_Call) Return() *MockStatusMetrics_SetStatusUpdateSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateSuccess_Call) RunAndReturn(run func(kind string)) *MockStatusMetrics_SetStatusUpdateSuccess_Call {
	_c.Run(run)
	return _c
}

// SetStatusUpdateTotal provides a mock function for the type MockStatusMetrics
func (_mock *MockStatusMetrics) SetStatusUpdateTotal(kind string) {
	_mock.Called(kind)
	return
}

// MockStatusMetrics_SetStatusUpdateTotal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStatusUpdateTotal'
type MockStatusMetrics_SetStatusUpdateTotal_Call struct {
	*mock.Call
}

// SetStatusUpdateTotal is a helper method to define mock.On call
//   - kind string
func (_e *MockStatusMetrics_Expecter) SetStatusUpdateTotal(kind interface{}) *MockStatusMetrics_SetStatusUpdateTotal_Call {
	return &MockStatusMetrics_SetStatusUpdateTotal_Call{Call: _e.mock.On("SetStatusUpdateTotal", kind)}
}

func (_c *MockStatusMetrics_SetStatusUpdateTotal_Call) Run(run func(kind string)) *MockStatusMetrics_SetStatusUpdateTotal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateTotal_Call) Return() *MockStatusMetrics_SetStatusUpdateTotal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStatusMetrics_SetStatusUpdateTotal_Call) RunAndReturn(run func(kind string)) *MockStatusMetrics_SetStatusUpdateTotal_Call {
	_c.Run(run)
	return _c
}
