apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver
  namespace: projectcontour
  labels:
    app.kubernetes.io/name: testserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: testserver
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: testserver
    spec:
      containers:
      - name: testserver
        image: ghcr.io/projectcontour/contour-authserver:v4
        imagePullPolicy: IfNotPresent
        command:
        - /contour-authserver
        args:
        - testserver
        - --address=:9443
        ports:
        - name: auth
          containerPort: 9443
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi

---

apiVersion: v1
kind: Service
metadata:
  name: testserver
  namespace: projectcontour
  labels:
    app.kubernetes.io/name: testserver
spec:
  ports:
  - name: auth
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: testserver
  type: ClusterIP
