apiVersion: apps/v1
kind: Deployment
metadata:
  name: htpasswd
  namespace: projectcontour-auth
  labels:
    app.kubernetes.io/name: htpasswd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: htpasswd
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: htpasswd
    spec:
      serviceAccountName: projectcontour-auth-htpasswd
      containers:
        - name: htpasswd
          image: ghcr.io/projectcontour/contour-authserver:v4
          imagePullPolicy: IfNotPresent
          command:
            - /contour-authserver
          args:
            - htpasswd
            - --address=:9443
            - --tls-ca-path=/tls/ca.crt
            - --tls-cert-path=/tls/tls.crt
            - --tls-key-path=/tls/tls.key
          ports:
            - name: auth
              containerPort: 9443
              protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: /tls
              readOnly: true
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
      volumes:
        - name: tls
          secret:
            secretName: contourcert
---
apiVersion: v1
kind: Service
metadata:
  name: htpasswd
  namespace: projectcontour-auth
  labels:
    app.kubernetes.io/name: htpasswd
spec:
  ports:
    - name: auth
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: htpasswd
  type: ClusterIP
