name: Build and push a release

on:
  push:
    tags:
    # Although these *look* like regex matches, they're not!
    # They are Go path.Match() expressions.
    # See https://golang.org/pkg/path/#Match for details.
    - 'v[0-9]*.[0-9]*.[0-9]'
    - 'v[0-9]*.[0-9]*.[0-9][0-9]'
    - 'v[0-9]*.[0-9]*.[0-9][0-9][0-9]'
    - 'v[0-9]*.[0-9]*.[0-9]*beta*'
    - 'v[0-9]*.[0-9]*.[0-9]*alpha*'
    - 'v[0-9]*.[0-9]*.[0-9]*rc*'

permissions:
  contents: read

env:
  GOPROXY: https://proxy.golang.org/
  GO_VERSION: 1.26.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      with:
        version: latest
    - name: Log in to GHCR
      uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push to GHCR
      env:
        REGISTRY: ghcr.io/${{ github.repository_owner }}
        TAG_LATEST: "false"
      run: |
        ./hack/actions/build-and-push-release-images.sh
  gateway-conformance-report:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-${{ github.job }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.job }}-go-
    - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    - name: add deps to path
      run: |
        ./hack/actions/install-kubernetes-toolchain.sh $GITHUB_WORKSPACE/bin
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: Gateway API conformance tests
      env:
        GENERATE_GATEWAY_CONFORMANCE_REPORT: "true"
      run: |
        export CONTOUR_E2E_IMAGE="ghcr.io/projectcontour/contour:$(git describe --tags)"
        make setup-kind-cluster run-gateway-conformance cleanup-kind
    - name: Upload gateway conformance report
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: gateway-conformance-report
        path: gateway-conformance-report/projectcontour-contour-*.yaml
