name: Build and push :main image

on:
  push:
    branches:
    - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      with:
        version: latest
    - name: Log in to GHCR
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push to GHCR
      env:
        REGISTRY: ghcr.io/${{ github.repository_owner }}
        VERSION: main
        TAG_LATEST: "false"
        PUSH_IMAGE: "true"
      run: |
        make multiarch-build
