# Stale issue and PR management
# See  https://github.com/marketplace/actions/close-stale-issues

name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-pr-stale: 14
        days-before-pr-close: 30
        stale-pr-label: 'lifecycle/stale'
        stale-pr-message: >
          Marking this PR stale since there has been no activity for 14
          days. It will be closed if there is no activity for another
          30 days.
        days-before-issue-stale: 60
        days-before-issue-close: 30
        stale-issue-label: 'lifecycle/stale'
        exempt-issue-labels: 'help wanted,good first issue,priority/important-soon'
        stale-issue-message: >
          Marking this Issue stale since there has been no activity for 60
          days. It will be closed if there is no activity for another
          30 days.
