# Stale issue and PR management
# See  https://github.com/marketplace/actions/close-stale-issues

name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: >
          Marking this PR stale since there has been no activity for 14
          days. It will be closed if there is no activity for another
          30 days.
        stale-pr-label: 'lifecycle/stale'
        days-before-stale: 14
        days-before-close: 30
        days-before-issue-stale: -1 # disable marking issues as stale
        days-before-issue-close: -1 # disable closing stale issues
