name: Trivy Scan

on:
  # Run weekly
  schedule:
  - cron: '0 12 * * 1'
  # Allow manual runs
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trivy-scan:
    strategy:
      matrix:
        branch:
        - main
        - release-1.33
        - release-1.32
        - release-1.31
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          ref: ${{ matrix.branch }}
      - uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          scanners: vuln
          scan-type: 'fs'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
      - uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v3.29.5
        with:
          sarif_file: 'trivy-results.sarif'
