name: 'Welcome New Contributors'

on:
  issues:
    types: [opened]
  # Workloads with pull_request_target and the GitHub Token secret should never include executing untrusted code
  # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  # And https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
  pull_request_target:
    types: [opened]

permissions:
  contents: read

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Greet the contributor'
      uses: garg3133/welcome-new-contributors@a38583ed8282e23d63d7bf919ca2d9fb95300ca6  # v1.2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Hey @contributor_name! Thanks for opening your first issue. We appreciate your contribution and welcome you to our community!
          We are glad to have you here and to have your input on Contour.
          You can also join us on [our mailing list](https://groups.google.com/g/project-contour) and [in our channel](https://kubernetes.slack.com/archives/C8XRH2R4J)
          in the [Kubernetes Slack Workspace](https://communityinviter.com/apps/kubernetes/community)
        pr-message: >
          Hi @contributor_name! Welcome to our community and thank you for opening your first Pull Request.
          Someone will review it soon. Thank you for committing to making Contour better.
          You can also join us on [our mailing list](https://groups.google.com/g/project-contour) and [in our channel](https://kubernetes.slack.com/archives/C8XRH2R4J)
          in the [Kubernetes Slack Workspace](https://communityinviter.com/apps/kubernetes/community)
