# This kustomization file disables all optional features.
# Run with:
#   kubectl kustomize --load-restrictor=LoadRestrictionsNone examples/optional-features/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../render/contour-gateway.yaml
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --disable-feature=extensionservices
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --disable-feature=grpcroutes
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --disable-feature=tlsroutes
    target:
      group: apps
      kind: Deployment
      name: contour
      version: v1
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: extensionservices.projectcontour.io
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: grpcroutes.gateway.networking.k8s.io
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: tlsroutes.gateway.networking.k8s.io
  # tcproutes is not handled by Contour at all
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: tcproutes.gateway.networking.k8s.io
  # udproutes is not handled by Contour at all
  - patch: |-
      $patch: delete
      apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: udproutes.gateway.networking.k8s.io
